wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681845162.158924
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      - 86
      2:
      - 2
      - 3
      - 12
      - 55
      - 86
      3:
      - 2
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 1
      - 5
